### ISSUE TITLE
tar file to large for dockerbuild to handle

### ISSUE THREAD

**Issue by anandkumarpatel** [apocas/dockerode#128]
I have a tar file which is 1.1gb, it fails to send to docker due to stack below. Is there a way to do this streaming and not using `fs.readFileSync`?

dockerode called like so:
```
docker.buildImage('file.tar', cb)
```
stack
```
buffer.js:194                                                                                                                                            
      this.parent = new SlowBuffer(this.length);                                                                                                         
                    ^                                                                                                                                    
RangeError: length > kMaxLength                                                                                                                          
    at new Buffer (buffer.js:194:21)                                                                                                                     
    at Object.fs.readFileSync (fs.js:309:16)                                                                                                             
    at Modem.dial (/source/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:117:17)                                                         
    at Docker.buildImage (/source/node_modules/dockerode/lib/docker.js:146:14)                                                                           
    at Builder.startImageBuild (/source/lib/steps/build.js:45:15)  
```

**Comment by anandkumarpatel** [comment]
I just found out you can pass tar stream as argument, might want to include that in the README and/or code comment?

**Comment by apocas** [comment]
There's already an example of this in the examples folder :)
https://github.com/apocas/dockerode/blob/master/examples/build/build_img_cwd.js

I guess I will also add a note to the readme saying it also accepts a stream.
