### ISSUE TITLE
docker.run(image, cmd) doesn't work when cmd array contains numbers

### ISSUE THREAD

**Issue by TDionis** [apocas/dockerode#238]
When you call

`docker.run('image_name', [ 42 ]) // Doesn't work`

the following error from docker-modem appears:
```
Error: HTTP code is 500 which indicates error: server error - json: cannot unmarshal array into Go value of type string
    at /src/node_modules/docker-modem/lib/modem.js:229:17
    at getCause (/src/node_modules/docker-modem/lib/modem.js:257:7)
    at Modem.buildPayload (/src/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/src/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:73:20)
    at IncomingMessage.emit (events.js:167:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
```

Solution: convert to string manually:
`docker.run('image_name', [ '42' ]) // Works`

**Comment by apocas** [comment]
json: cannot unmarshal array into Go value of type string
"Go" aKa not us :)

Yup, Docker's RAPI expect's string.
Nothing we can do here :)
