### ISSUE TITLE
`container.putArchive()` doesn't work

### ISSUE THREAD

**Issue by jankeromnes** [apocas/dockerode#240]
I'm not able to use `container.putArchive()` with dockerode v2.2.10 and Docker version 1.6.2:

    var dockerode = require('dockerode');
    var tar = require('tar-stream');
    
    var docker = new dockerode({ /* Docker host options */ });
    
    var container = docker.getContainer(/* Existing container ID */);
    
    container.inspect(function (error, data) {
      console.log('DATA', data); // This shows info about a real container: It actually exists
    
      var pack = tar.pack();
      pack.entry({ name: 'TESTFILE' }, 'TEST');
      pack.finalize();
    
      var chunks = [];
      pack.on('data', function (chunk) { chunks.push(chunk); });
      pack.on('end', function () {
    
        var buffer = Buffer.concat(chunks);
    
        container.putArchive(buffer, { path: '/tmp' }, function (error, response) {
          if (error) {
            console.error(error); // The error is "Error: HTTP code is 404 which indicates error: no such container - 404 page not found"
          }
        });
    
      });
    });

Stack trace of the error:

    error { Error: HTTP code is 404 which indicates error: no such container - 404 page not found
    
        at /home/janx/janitor/node_modules/docker-modem/lib/modem.js:229:17
        at IncomingMessage.<anonymous> (/home/janx/janitor/node_modules/docker-modem/lib/modem.js:254:9)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:926:12)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9) reason: 'no such container', statusCode: 404, json: null }

**Comment by jankeromnes** [comment]
Actually my Docker version si too old for this: The `archive` endpoint was added in [Docker Remote API v1.20](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.20/#extract-an-archive-of-files-or-folders-to-a-directory-in-a-container) whereas my version 1.6.2 offers Remote API v1.16.
