### ISSUE TITLE
when running tests - failed to verify image error

### ISSUE THREAD

**Issue by DinisCruz** [apocas/dockerode#247]
when trying to run the tests I just had this error:

```
Error: HTTP code is 500 which indicates error: server error - failed to verify image: sha256:4ae3d38a34c61430d7f6d60d28a7aed5d45d2bc76baeff86f1d5823cf6df77a7
```

Here is the full error stack
```
npm test

> dockerode@2.2.10 test /Users/diniscruz/_Dev_Tests/dockerode
> ./node_modules/mocha/bin/mocha -R spec

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
Trying TCP connection...


  #container
    1) "before all" hook

  0 passing (74ms)
  1 failing

  1) #container "before all" hook:
     Error: HTTP code is 500 which indicates error: server error - failed to verify image: sha256:4ae3d38a34c61430d7f6d60d28a7aed5d45d2bc76baeff86f1d5823cf6df77a7

      at /Users/diniscruz/_Dev_Tests/dockerode/node_modules/docker-modem/lib/modem.js:229:17
      at getCause (/Users/diniscruz/_Dev_Tests/dockerode/node_modules/docker-modem/lib/modem.js:257:7)
      at Modem.buildPayload (/Users/diniscruz/_Dev_Tests/dockerode/node_modules/docker-modem/lib/modem.js:228:5)
      at IncomingMessage.<anonymous> (/Users/diniscruz/_Dev_Tests/dockerode/node_modules/docker-modem/lib/modem.js:204:14)
      at emitNone (events.js:72:20)
      at IncomingMessage.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:905:12)
      at nextTickCallbackWith2Args (node.js:455:9)
      at process._tickCallback (node.js:369:17)
```

Here are the commands I executed (in a terminal with docker setup, i.e. ```docker ps``` works)

```
git clone git@github.com:apocas/dockerode.git
cd dockerode
npm install
npm test
```

**Comment by DinisCruz** [comment]
after, rebooting docker (as per this SO thread http://stackoverflow.com/questions/28301151/docker-pull-error) using 

```docker-machine restart default && eval "$(docker-machine env default)"```

running 

```docker pull ubuntu:latest```

now works:

```
latest: Pulling from library/ubuntu
6d28225f8d96: Pull complete 
166102ec41af: Pull complete 
d09bfba2bd6a: Pull complete 
c80dad39a6c0: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:5718d664299eb1db14d87db7bfa6945b28879a67b74f36da3e34f5914866b71c
Status: Downloaded newer image for ubuntu:latest
````

and so do the tests 

```
> dockerode@2.2.10 test /Users/diniscruz/_Dev_Tests/dockerode
> ./node_modules/mocha/bin/mocha -R spec

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
Trying TCP connection...


  #container
    #inspect
      ✓ should inspect a container 
      ✓ should inspect a container with opts 
    #archive
      ✓ should get an archive inside the container (48ms)
      ✓ should put an archive inside the container (102ms)
      ✓ should inspect an archive inside the container (40ms)
    #start
      ✓ should start a container (265ms)
    #resize
      ✓ should resize tty a container 
    #update
      ✓ should update a container 
    #stats
      ✓ should get container stats 
    #stdin
      ✓ should support attach with tty enable writing 1000 bytes (774ms)
      ✓ should support attach with tty disabled writing 5000 bytes (778ms)
    #attach
      ✓ should attach and wait for a container (800ms)
      ✓ should support attach with stdin enable (780ms)
      ✓ should support attach with hijack and stdin enable (831ms)
    #restart
      ✓ should restart a container (971ms)
    #export
      ✓ should export a container 
    #top
      ✓ should return top 

.... more ...


  #networks
    #connect
      ✓ should connect a container to a network (128ms)
    #inspect
      ✓ should inspect a network 
    #disconnect
      ✓ should disconnect a container to a network (105ms)

  util
    #parseRepositoryTag
      ✓ should parse "root" 
      ✓ should parse "root:tag" 
      ✓ should parse "root@sha256:1234abc" 
      ✓ should parse "user/repo" 
      ✓ should parse "user/repo:tag" 
      ✓ should parse "urlx:5000/repo" 
      ✓ should parse "url:5000/repo:tag" 
    .extend
      ✓ accepts multiple object arguments 


  71 passing (1m)
````

closing issue since the prob was local

**Comment by DinisCruz** [comment]
note: I believe the root cause of the 'failed to verify image' error was the fact that I didn't had the ubuntu image on docker instance
