### ISSUE TITLE
Unable to run exec in a docker container

### ISSUE THREAD

**Issue by jayantbh** [apocas/dockerode#263]
I'm unable to run exec in a docker container.

It keeps throwing this:
`/open /proc/6/status: no such file or directory`

Even your example [here](https://github.com/apocas/dockerode/blob/master/examples/exec_running_container.js) throws the same error.

This is my code:

``` javascript
var docker = new Docker();

var username = "test_user";
var container;
var containerId;

if (storage.getItem(username)) {
    containerId = storage.getItem(username);
    container = docker.getContainer(containerId);
    // console.log(container);
    containerHandler(container);
}
else {
    docker.createContainer({Image: 'ubuntu', Cmd: ['/bin/bash']}, function (err, container) {
        storage.setItem(username, container.id);
        containerHandler(container);
    });
}

function containerHandler(container) {
    container.start(function (err, data) {
        console.log("Started: ", data);
        command(container, "ls");
    });
}

function command(container, cmd) {
    var options = {
        'AttachStdout': true,
        'AttachStderr': true,
        'Tty': false,
        Cmd: ["bash", "-c", "ls"]
    };
    container.exec(options, function (err, exec) {
        if (err) return;

        var attach_opts = {'Detach': false, 'Tty': false, stream: true, stdin: true, stdout: true, stderr: true};
        exec.start(attach_opts, function (err, stream) {
            if (err) return;

            stream.setEncoding('utf8');
            stream.pipe(process.stdout);
        });
    });
}
```

What am I doing wrong? ;_;

**Comment by apocas** [comment]
Humm.

What Docker version are you using?
Could you please do a npm test in your system?

https://github.com/apocas/dockerode/blob/master/test/container.js#L546 - check this test

**Comment by jayantbh** [comment]
Nevermind, it works now. It's a weird world. Thanks for your time though. :)

**Comment by jayantbh** [comment]
Nope. Still there.

**Comment by jayantbh** [comment]
Docker version 1.9.1, build a34a1d5
```
jayantbhawal@px:~/Projects/dockerode$ npm test
(node:18696) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:18696) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:18696) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm info it worked if it ends with ok
npm info using npm@3.9.5
npm info using node@v6.2.2
(node:18696) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm info lifecycle dockerode@2.3.0~pretest: dockerode@2.3.0
npm info lifecycle dockerode@2.3.0~test: dockerode@2.3.0

> dockerode@2.3.0 test /home/jayantbhawal/Projects/dockerode
> ./node_modules/mocha/bin/mocha -R spec

(node:18707) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.


  #container
    #inspect
      ✓ should inspect a container 
      ✓ should inspect a container with opts 
    #archive
      ✓ should get an archive inside the container (55ms)
      ✓ should put an archive inside the container (77ms)
      ✓ should inspect an archive inside the container (44ms)
    #start
      ✓ should start a container (426ms)
    #resize
      ✓ should resize tty a container 
    #update
      1) should update a container
    #stats
      ✓ should get container stats 
    #stdin
      ✓ should support attach with tty enable writing 1000 bytes (1137ms)
      ✓ should support attach with tty disabled writing 5000 bytes (1193ms)
    #attach
      ✓ should attach and wait for a container (1273ms)
      ✓ should support attach with stdin enable (1070ms)
      ✓ should support attach with hijack and stdin enable (1138ms)
    #restart
      ✓ should restart a container (839ms)
    #export
      ✓ should export a container 
    #top
      ✓ should return top 
    #changes
      ✓ should container changes 
    #logs
      ✓ should get the logs for a container as a stream 
    #exec
      ✓ should run exec on a container (58ms)
      ✓ should allow exec stream hijacking on a container 
    #commit
      ✓ should commit a container 
    #stop
      ✓ should stop a container (411ms)

  #non-responsive container
    #restart
      ✓ forced after timeout (455ms)
    #stop
      ✓ forced after timeout (10497ms)

  #docker
    #checkAuth
      ✓ should fail auth (1130ms)
    #buildImage
      ◦ should build image from file: {"stream":"Step 1 : FROM ubuntu\n"}
{"stream":" ---\u003e e96075b1f789\n"}
{"stream":"Step 2 : MAINTAINER Pedro Dias\n"}
{"stream":" ---\u003e Running in 23ece4aea49b\n"}
{"stream":" ---\u003e 0e44888010c8\n"}
{"stream":"Removing intermediate container 23ece4aea49b\n"}
{"stream":"Step 3 : RUN uptime\n"}
{"stream":" ---\u003e Running in d80bb886ac52\n"}
{"stream":" 01:23:21 up  2:38,  0 users,  load average: 0.99, 0.57, 0.40\n"}
{"stream":" ---\u003e 1a1a9117d612\n"}
{"stream":"Removing intermediate container d80bb886ac52\n"}
{"stream":"Successfully built 1a1a9117d612\n"}
      ✓ should build image from file (1857ms)
      ◦ should build image from readable stream: {"stream":"Step 1 : FROM ubuntu\n"}
{"stream":" ---\u003e e96075b1f789\n"}
{"stream":"Step 2 : MAINTAINER Pedro Dias\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 0e44888010c8\n"}
{"stream":"Step 3 : RUN uptime\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 1a1a9117d612\n"}
{"stream":"Successfully built 1a1a9117d612\n"}
      ✓ should build image from readable stream 
    #loadImage
      ✓ should load image from readable stream 
    #getEvents
      ✓ should get events 
    #getPing
      ✓ should ping server 
    #testTimeout
      ✓ should timeout 
    #pull
      ◦ should pull image from remote source: {"status":"Pulling from library/ubuntu","id":"14.04"}
{"status":"Pulling fs layer","progressDetail":{},"id":"b6b59ba2b1e5"}{"status":"Pulling fs layer","progressDetail":{},"id":"401f6712926f"}{"status":"Pulling fs layer","progressDetail":{},"id":"3667a1481f9c"}{"status":"Pulling fs layer","progressDetail":{},"id":"2e82ca87ee2d"}{"status":"Pulling fs layer","progressDetail":{},"id":"9eb73e5ef68f"}{"status":"Downloading","progressDetail":{"current":16384,"total":71563},"progress":"[===========\u003e                                       ] 16.38 kB/71.56 kB","id":"401f6712926f"}{"status":"Downloading","progressDetail":{"current":32768,"total":71563},"progress":"[======================\u003e                            ] 32.77 kB/71.56 kB","id":"401f6712926f"}{"status":"Downloading","progressDetail":{"current":41992,"total":71563},"progress":"[=============================\u003e                     ] 41.99 kB/71.56 kB","id":"401f6712926f"}{"status":"Downloading","progressDetail":{"current":58376,"total":71563},"progress":"[========================================\u003e          ] 58.38 kB/71.56 kB","id":"401f6712926f"}{"status":"Downloading","progressDetail":{"current":71563,"total":71563},"progress":"[==================================================\u003e] 71.56 kB/71.56 kB","id":"401f6712926f"}{"status":"Verifying Checksum","progressDetail":{},"id":"401f6712926f"}{"status":"Download complete","progressDetail":{},"id":"401f6712926f"}{"status":"Downloading","progressDetail":{"current":32,"total":32},"progress":"[==================================================\u003e]     32 B/32 B","id":"9eb73e5ef68f"}{"status":"Verifying Checksum","progressDetail":{},"id":"9eb73e5ef68f"}{"status":"Download complete","progressDetail":{},"id":"9eb73e5ef68f"}{"status":"Downloading","progressDetail":{"current":365,"total":365},"progress":"[==================================================\u003e]    365 B/365 B","id":"3667a1481f9c"}{"status":"Verifying Checksum","progressDetail":{},"id":"3667a1481f9c"}{"status":"Download complete","progressDetail":{},"id":"3667a1481f9c"}{"status":"Downloading","progressDetail":{"current":680,"total":680},"progress":"[==================================================\u003e]    680 B/680 B","id":"2e82ca87ee2d"}{"status":"Verifying Checksum","progressDetail":{},"id":"2e82ca87ee2d"}{"status":"Download complete","progressDetail":{},"id":"2e82ca87ee2d"}{"status":"Downloading","progressDetail":{"current":533813,"total":65699069},"progress":"[\u003e                                                  ] 533.8 kB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Downloading","progressDetail":{"current":1065797,"total":65699069},"progress":"[\u003e                                                  ] 1.066 MB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Downloading","progressDetail":{"current":1606469,"total":65699069},"progress":"[=\u003e                                                 ] 1.606 MB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Downloading","progressDetail":{"current":2147141,"total":65699069},"progress":"[=\u003e                                                 ] 2.147 MB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Downloading","progressDetail":{"current":65611597,"total":65699069},"progress":"[=================================================\u003e ] 65.61 MB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Downloading","progressDetail":{"current":65699069,"total":65699069},"progress":"[==================================================\u003e]  65.7 MB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Verifying Checksum","progressDetail":{},"id":"b6b59ba2b1e5"}{"status":"Download complete","progressDetail":{},"id":"b6b59ba2b1e5"}{"status":"Extracting","progressDetail":{"current":557056,"total":65699069},"progress":"[\u003e                                                  ] 557.1 kB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Extracting","progressDetail":{"current":1114112,"total":65699069},"progress":"[\u003e                                                  ] 1.114 MB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Extracting","progressDetail":{"current":1671168,"total":65699069},"progress":"[=\u003e                                                 ] 1.671 MB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Extracting","progressDetail":{"current":2228224,"total":65699069},"progress":"[=\u003e                                                 ] 2.228 MB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Extracting","progressDetail":{"current":2785280,"total":65699069},"progress":"[==\u003e                                                ] 2.785 MB/65.7 MB","id":"b6b59ba2b1e5"}{"status":"Extracting","progressDetail":{"current":32,"total":32},"progress":"[==================================================\u003e]     32 B/32 B","id":"9eb73e5ef68f"}{"status":"Pull complete","progressDetail":{},"id":"9eb73e5ef68f"}{"status":"Digest: sha256:ad7a9c790ae1adbec4832f6c31b638454f360125e9f9b3ca919f749e590d7037"}
{"status":"Status: Downloaded newer image for ubuntu:14.04"}
      ✓ should pull image from remote source (22916ms)
      ✓ should pull image from remote source using followProgress (3583ms)
      ✓ should pull image from remote source using followProgress and firing only in the end (3734ms)
      ✓ should pull image from remote source using followProgress and pause (3881ms)
    #run
      ◦ should emit partial data: Linux b4a66c060bed 4.2.0-41-generic #48-Ubuntu SMP Fri Jun 24 11:28:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
      ✓ should emit partial data (2584ms)
      ◦ should run a command: Linux 5cadb571a04f 4.2.0-41-generic #48-Ubuntu SMP Fri Jun 24 11:28:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
      ✓ should run a command (1487ms)
      ◦ should run a command with create options: Linux 7a4e660a25c0 4.2.0-41-generic #48-Ubuntu SMP Fri Jun 24 11:28:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
      ✓ should run a command with create options (8200ms)
    #createVolume
      ✓ should create and remove a volume 
    #createNetwork
      ✓ should create and remove a network (1048ms)
    #createContainer
      ✓ should create and remove a container (394ms)
    #createImage
      ◦ should create an image: {"status":"Pulling from library/ubuntu","id":"14.04"}
{"status":"Digest: sha256:ad7a9c790ae1adbec4832f6c31b638454f360125e9f9b3ca919f749e590d7037"}
{"status":"Status: Image is up to date for ubuntu:14.04"}
      ✓ should create an image (3370ms)
    #importImage
      ◦ should import an image from a tar archive: {"status":"ad14bb1d556137b725864f0f9370e16fbbf694d9a34b4b62071cf4134ba900fd"}
      ✓ should import an image from a tar archive 
    #listContainers
      ✓ should list containers 
    #listImages
      ✓ should list images 
    #listVolumes
      ✓ should list volumes 
    #listNetworks
      ✓ should list networks 
    #version
      ✓ should return version 
    #searchImages
      ✓ should return search results (1623ms)
    #info
      ✓ should return system info (515ms)
    #labelsAndFilters
      ✓ should create a container with an empty value label (372ms)
      ✓ should create a container with an assigned value label (270ms)
      ✓ should query containers filtering by valueless labels 
      ✓ should query containers filtering by valued labels 
      ✓ should query containers filtering by map of valued labels 

  #image
    #inspect
      ✓ should inspect a image 
    #history
      ✓ should get image history 
    #get
      ✓ should get an image (1897ms)

  #networks
    #connect
      ✓ should connect a container to a network (333ms)
    #inspect
      ✓ should inspect a network 
    #disconnect
      ✓ should disconnect a container to a network (354ms)

  #swarm
    #initSwarm
      2) should init swarm
    #Services
      3) should create service
      4) should list services
      5) should inspect service
      6) should update service
      7) should delete service
    #tasks
      #listTasks
        8) should list tasks
    #nodes
      #listNodes
        9) should list nodes
        10) should inspect node
    #leaveSwarm
      11) should leave swarm

  util
    #parseRepositoryTag
      ✓ should parse "root" 
      ✓ should parse "root:tag" 
      ✓ should parse "root@sha256:1234abc" 
      ✓ should parse "user/repo" 
      ✓ should parse "user/repo:tag" 
      ✓ should parse "urlx:5000/repo" 
      ✓ should parse "url:5000/repo:tag" 
    .extend
      ✓ accepts multiple object arguments 


  69 passing (1m)
  11 failing

  1) #container #update should update a container:
     Uncaught AssertionError: expected [Error: (HTTP code 404) no such container - 404 page not found
 ] to be null
  

  2) #swarm #initSwarm should init swarm:
     Uncaught AssertionError: expected [Error: (HTTP code 404) unexpected - 404 page not found
 ] to be null
  

  3) #swarm #Services should create service:
     Uncaught AssertionError: expected [Error: (HTTP code 404) unexpected - 404 page not found
 ] to be null
  

  4) #swarm #Services should list services:
     Uncaught AssertionError: expected [Error: (HTTP code 404) unexpected - 404 page not found
 ] to be null
  

  5) #swarm #Services should inspect service:
     TypeError: Cannot read property 'inspect' of undefined
      at Context.<anonymous> (/home/jayantbhawal/Projects/dockerode/test/swarm.js:102:14)
      at Test.Runnable.run (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runnable.js:194:15)
      at Runner.runTest (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:355:10)
      at /home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:401:12
      at next (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:281:14)
      at /home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:290:7
      at next (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:234:23)
      at Immediate._onImmediate (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:258:5)
      at tryOnImmediate (timers.js:543:15)
      at processImmediate [as _immediateCallback] (timers.js:523:5)

  6) #swarm #Services should update service:
     TypeError: Cannot read property 'update' of undefined
      at Context.<anonymous> (/home/jayantbhawal/Projects/dockerode/test/swarm.js:140:14)
      at Test.Runnable.run (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runnable.js:194:15)
      at Runner.runTest (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:355:10)
      at /home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:401:12
      at next (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:281:14)
      at /home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:290:7
      at next (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:234:23)
      at Immediate._onImmediate (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:258:5)
      at tryOnImmediate (timers.js:543:15)
      at processImmediate [as _immediateCallback] (timers.js:523:5)

  7) #swarm #Services should delete service:
     TypeError: Cannot read property 'remove' of undefined
      at Context.<anonymous> (/home/jayantbhawal/Projects/dockerode/test/swarm.js:151:14)
      at Test.Runnable.run (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runnable.js:194:15)
      at Runner.runTest (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:355:10)
      at /home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:401:12
      at next (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:281:14)
      at /home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:290:7
      at next (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:234:23)
      at Immediate._onImmediate (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:258:5)
      at tryOnImmediate (timers.js:543:15)
      at processImmediate [as _immediateCallback] (timers.js:523:5)

  8) #swarm #tasks #listTasks should list tasks:
     Uncaught AssertionError: expected [Error: (HTTP code 404) unexpected - 404 page not found
 ] to be null
  

  9) #swarm #nodes #listNodes should list nodes:
     Uncaught AssertionError: expected [Error: (HTTP code 404) unexpected - 404 page not found
 ] to be null
  

  10) #swarm #nodes #listNodes should inspect node:
     TypeError: Cannot read property 'inspect' of undefined
      at Context.<anonymous> (/home/jayantbhawal/Projects/dockerode/test/swarm.js:208:13)
      at Test.Runnable.run (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runnable.js:194:15)
      at Runner.runTest (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:355:10)
      at /home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:401:12
      at next (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:281:14)
      at /home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:290:7
      at next (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:234:23)
      at Immediate._onImmediate (/home/jayantbhawal/Projects/dockerode/node_modules/mocha/lib/runner.js:258:5)
      at tryOnImmediate (timers.js:543:15)
      at processImmediate [as _immediateCallback] (timers.js:523:5)

  11) #swarm #leaveSwarm should leave swarm:
     Uncaught AssertionError: expected [Error: (HTTP code 404) unexpected - 404 page not found
 ] to be null
  



npm info lifecycle dockerode@2.3.0~test: Failed to exec test script
npm ERR! Test failed.  See above for more details.
```

**Comment by apocas** [comment]
Run this updated example: https://github.com/apocas/dockerode/blob/master/examples/exec_running_container.js and pingback :)

**Comment by JeromeVi** [comment]
@jayantbh  could you answer if you have finish this issue ? Because I'm +/- in this situation
