### ISSUE TITLE
Exec error in container returning 404

### ISSUE THREAD

**Issue by DaneEveritt** [apocas/dockerode#317]
I'm actually not sure if this is an issue with Dockerode, or with Docker itself, but we encountered this strange issue today. We had a malformed image that was trying to call a bash script, but bash was not in the container.

However, it appears that Dockerode interpreted the error as no container existing, even though the container does exist on the system.

The error returned by `Dockerode`:
```
{ Error: (HTTP code 404) no such container - invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/bin/bash\\\": stat /bin/bash: no such file or directory\"\n" 
    at /srv/daemon/node_modules/docker-modem/lib/modem.js:229:17
    at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:259:7)
    at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  reason: 'no such container',
  statusCode: 404,
  json: { message: 'invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \\"exec: \\\\\\"/bin/bash\\\\\\": stat /bin/bash: no such file or directory\\"\\n"' } }
```

The response when using `docker inspect` on the container:
```
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 127,
            "Error": "invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"/bin/bash\\\\\\\": stat /bin/bash: no such file or directory\\\"\\n\"",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
```

`docker -v`: `Docker version 1.12.3, build 6b644ec`
`node -v`: `v6.9.1`
`npm -v `: `3.10.8`

`docker info`:
```
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 17
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 91
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.842 GiB
Name: daemon
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by DaneEveritt** [comment]
Removing the container and attempting the same returns an expected 404 error:

```
{ Error: (HTTP code 404) no such container - No such container: 2a7fd8912a32 
    at /srv/daemon/node_modules/docker-modem/lib/modem.js:229:17
    at getCause (/srv/daemon/node_modules/docker-modem/lib/modem.js:259:7)
    at Modem.buildPayload (/srv/daemon/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  reason: 'no such container',
  statusCode: 404,
  json: { message: 'No such container: 2a7fd8912a32' } }
```

**Comment by apocas** [comment]
Docker is returning a 404.
We map the HTTP code to a generic message using the official documentation, then we append additional error output that Docker sometimes returns.
This is way you saw "invalid header field value oci runtime er..." appended.

https://docs.docker.com/engine/api/v1.33/#operation/ContainerExec
Documentation specifies 404 to "no such container" :/
