### ISSUE TITLE
Docker.listContainers can't get the containers

### ISSUE THREAD

**Issue by JeromeVi** [apocas/dockerode#323]
I'm actually trying to run a Meteor app in a container (it runs) and in this app I want to list all the container that I have in Docker. If I run this app outside of a container there is no problem I can list my containers, stop them, start them... 
But when I put this app in a container I got this error:
```
app_1    | Exception in callback of async function: TypeError: Cannot read property 'forEach' of null
app_1    |     at server/main.js:71:5
app_1    |     at runWithEnvironment (packages/meteor.js:1176:24)
```

And the code of this part is this one: 
```
/**
* this add some infos about our docker's containers in the collection
**/
addInfos = Meteor.bindEnvironment(function(){
  /* Add the id, name and the state in the collection */
      //just in case because sometimes docker crash
      while( docker == null ){
        setTimeout(function(){
          docker = new Docker({socketPath: '/var/run/docker.sock'});
        }, 1000);
      }
  docker.listContainers({all: true},Meteor.bindEnvironment(function (err, containers) {
    //containers is null if it runs in docker
    containers.forEach( Meteor.bindEnvironment(function (containerInfo) {
      InfosContainers.insert({
        idContainer: containerInfo.Id,
        nameContainer: containerInfo.Names[0],
        stateContainer: containerInfo.State
      });
    }));
  }));
});
```

Someone here know why it does this ?

**Comment by JeromeVi** [comment]
The problem came from the image that I used for Meteor now it's ok
