### ISSUE TITLE
Can't start a container with the given example of binding a volume

### ISSUE THREAD

**Issue by Skarlso** [apocas/dockerode#359]
When I'm trying to do this:

```javascript
        // config bind is : /Users/user/.miner_bind
        container.start({'Binds':[config.bind + '/:/data']}, function (err, data) {
            if (!err) {
                console.log('Container started.');
                tmux.run(con.Name.replace('/', ''));
            } else {
                console.log(err);
                process.exit(1);
            }
        });
```

I'm getting this:

```bash
Binding to location: /Users/user/.miner_world/:/data
{ message: 'starting container with non-empty request body was deprecated since v1.10 and removed in v1.12' }
{ Error: (HTTP code 400) unexpected - starting container with non-empty request body was deprecated since v1.10 and removed in v1.12
    at /Users/user/minecraft_server/miner/node_modules/docker-modem/lib/modem.js:240:17
    at getCause (/Users/user/minecraft_server/miner/node_modules/docker-modem/lib/modem.js:270:7)
    at Modem.buildPayload (/Users/user/minecraft_server/miner/node_modules/docker-modem/lib/modem.js:239:5)
    at IncomingMessage.<anonymous> (/Users/user/minecraft_server/miner/node_modules/docker-modem/lib/modem.js:214:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  reason: undefined,
  statusCode: 400,
  json: { message: 'starting container with non-empty request body was deprecated since v1.10 and removed in v1.12' } }
```

**Comment by apocas** [comment]
Check the updated example.

**Comment by Skarlso** [comment]
Yes!! This worked. Thanks. Now I can continue. :) 👍
