### ISSUE TITLE
`.buildImage` appears to connect to localhost regardless

### ISSUE THREAD

**Issue by Gisleburt** [apocas/dockerode#424]
Trying to build an image using minikube (which runs in a VirtualBox VM) rather than any native Docker.

minikube docker-env:
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://x.y.z.w:2376"
export DOCKER_CERT_PATH="/Users/...me.../.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)
```
Converted to Opts:
```
{
  host: 'tcp://x.y.z.w,
  port: '2376',
  version: 'v1.23',
  ca: <Buffer ... >,
  cert: <Buffer ... >,
  key: <Buffer ... > 
}
```
Resulting `new Docker` object:
```
Docker {
  modem: 
   Modem {
     socketPath: undefined,
     host: 'tcp://x.y.z.w',
     port: '2376',
     version: 'v1.23',
     key: <Buffer ... >,
     cert: <Buffer ... >,
     ca: <Buffer ... >,
     timeout: undefined,
     checkServerIdentity: undefined,
     protocol: 'https',
     Promise: [Function: Promise]
  }
}
```
`docker.buildImage()` error:
```
{
  Error: connect ECONNREFUSED 127.0.0.1:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443
}
```
I'm sure I've missed some facet, but would love some help.

Quickly want to add thank you for providing an easy to use wrapper. Other than this, my only problems have been from a faliure to RTFM (which this might be too 😊).

**Comment by mmmpie** [comment]
Dockerode does not support putting the protocol in the `host` field. The `protocol` field only accepts `http|https`, not `tcp`.

```
{
  host: 'x.y.z.w',
  protocol: 'https'
}
```
