### ISSUE TITLE
The requested URL /containers/create was not found.

### ISSUE THREAD

**Issue by hifall** [apocas/dockerode#465]
When I create a docker passing timeout, then run a container like this:
```
    const docker = new Docker({ timeout: 300 });
    docker.run(
        'ubuntu',
        ['bash',
         '-c',
         command],
        process.stdout,
        {
            Tty:false,
            'Volumes': {
                '/mnt': {}
            },
            'HostConfig': {
                'Binds': ['/var/repl:/mnt']
            }
        },
        function (err, data, container) {
            console.log(err);
            containerLogs(container, function(logText) {
                done(logText);
            });
        }
    );
```

I get this error:
```
Jun 26 14:18:33 mx nodejs-repl-server[21777]: { Error: (HTTP code 404) no such container - <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
Jun 26 14:18:33 mx nodejs-repl-server[21777]: <html><head>
Jun 26 14:18:33 mx nodejs-repl-server[21777]: <title>404 Not Found</title>
Jun 26 14:18:33 mx nodejs-repl-server[21777]: </head><body>
Jun 26 14:18:33 mx nodejs-repl-server[21777]: <h1>Not Found</h1>
Jun 26 14:18:33 mx nodejs-repl-server[21777]: <p>The requested URL /containers/create was not found on this server.</p>
Jun 26 14:18:33 mx nodejs-repl-server[21777]: <hr>
Jun 26 14:18:33 mx nodejs-repl-server[21777]: <address>Apache Server at localhost Port 80</address>
Jun 26 14:18:33 mx nodejs-repl-server[21777]: </body></html>
Jun 26 14:18:33 mx nodejs-repl-server[21777]:  
Jun 26 14:18:33 mx nodejs-repl-server[21777]:     at /var/repl/node_modules/docker-modem/lib/modem.js:254:17
Jun 26 14:18:33 mx nodejs-repl-server[21777]:     at getCause (/var/repl/node_modules/docker-modem/lib/modem.js:284:7)
Jun 26 14:18:33 mx nodejs-repl-server[21777]:     at Modem.buildPayload (/var/repl/node_modules/docker-modem/lib/modem.js:253:5)
Jun 26 14:18:33 mx nodejs-repl-server[21777]:     at IncomingMessage.<anonymous> (/var/repl/node_modules/docker-modem/lib/modem.js:229:14)
Jun 26 14:18:33 mx nodejs-repl-server[21777]:     at emitNone (events.js:111:20)
Jun 26 14:18:33 mx nodejs-repl-server[21777]:     at IncomingMessage.emit (events.js:208:7)
Jun 26 14:18:33 mx nodejs-repl-server[21777]:     at endReadableNT (_stream_readable.js:1064:12)
Jun 26 14:18:33 mx nodejs-repl-server[21777]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Jun 26 14:18:33 mx nodejs-repl-server[21777]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Jun 26 14:18:33 mx nodejs-repl-server[21777]:   reason: 'no such container',
Jun 26 14:18:33 mx nodejs-repl-server[21777]:   statusCode: 404,
Jun 26 14:18:33 mx nodejs-repl-server[21777]:   json: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /containers/create was not found on this server.</p>\n<hr>\n<address>Apache Server at localhost Port 80</address>\n</body></html>\n' }
Jun 26 14:18:33 mx nodejs-repl-server[21777]: /var/repl/server.js:17
```

I am not sure why specifying a timeout causes the create endpoint to not be found. Can anyone help me?

Thanks!

**Comment by apocas** [comment]
Apache Server at localhost Port 80 ?
