### ISSUE TITLE
Stream for service.update

### ISSUE THREAD

**Issue by tanishq-dubey** [apocas/dockerode#484]
It seems like I cannot have a stream of a service being updated

My code
```
const service = docker.getService(s);
service.update(opts, (erru, datau) => {
docker.modem.followProgress(datau, onFinished, onProgress);

function onFinished(errf, output) {
...
}
```

Error:
```
/usr/src/app/node_modules/docker-modem/lib/modem.js:316
 stream.pipe(parser);
        ^

 TypeError: stream.pipe is not a function
   at Modem.followProgress (/usr/src/app/node_modules/docker-modem/lib/modem.js:316:10)
   at service.update (/usr/src/app/app.js:171:36)
   at /usr/src/app/node_modules/dockerode/lib/service.js:128:7
   at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:270:7)
   at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:229:14)
   at IncomingMessage.emit (events.js:187:15)
   at endReadableNT (_stream_readable.js:1092:12)
   at process._tickCallback (internal/process/next_tick.js:63:19)
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! smokestack@1.0.0 start: `node app.js`
 npm ERR! Exit status 1
```

**Comment by superhero** [comment]
update in general seem to fail, maybe related?

Wrote on stackoverflow: https://stackoverflow.com/questions/55513043/nodejs-application-in-docker-swarm-service-update-has-no-effect

**Comment by somq** [comment]
Any news or workaround on this?

**Comment by apocas** [comment]
service.update does not return a stream.

https://docs.docker.com/engine/api/v1.41/#operation/ServiceUpdate
