### ISSUE TITLE
image.push fails with docker swarm

### ISSUE THREAD

**Issue by thenengah** [apocas/dockerode#509]
# Error

```
{ 
  Error: '(HTTP code 404) no such image - No such image: {account-id}.dkr.ecr.us-east-1.amazonaws.com/{repo}:{tag}'
    at /root/labs/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/root/labs/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/root/labs/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/root/labs/node_modules/docker-modem/lib/modem.js:232:14)
    at Object.apply (/root/labs/node_modules/harmony-reflect/reflect.js:2064:37)
    at IncomingMessage.emit (events.js:187:15)
    at Object.apply (/root/labs/node_modules/harmony-reflect/reflect.js:2064:37)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at Object.apply (/root/labs/node_modules/harmony-reflect/reflect.js:2064:37)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  reason: 'no such image',
  statusCode: 404,
  json: { 
    message: 'No such image: {account-id}.dkr.ecr.us-east-1.amazonaws.com/{repo}:{tag}' 
  }
} 
```

# Background

I have the code below working in development (because everything is on one machine), but on production I have a docker swarm with managers and worker nodes. When I run docker commit it creates a snapshot and running docker image ls confirms this, but when I try to push to a private registry (ecr) docker cannot find the image. I guess this is because the image is on the worker and the manager cannot find it, or the image is on the manager and the worker cannot find it. 

It appears that commit saves the image on the node with the container, but then trying to push that image to a registry fails because the master node doesn't know where the image is. 

Is it possible to specify which node to push from as that would solve the problem? How else can I fix this issue?

```
const Docker = require('dockerode')
const AWS = require('aws-sdk')

const {
  DOCKER_HOST,
  DOCKER_PORT,
  DOCKER_PROTOCOL,
  AWS_ECR_REGION,
  AWS_ECR_SECRET_ACCESS_KEY,
  AWS_ECR_ACCESS_KEY_ID,
  AWS_ECR_REPO
} = process.env

const docker = new Docker({
  host: DOCKER_HOST,
  port: DOCKER_PORT,
  protocol: DOCKER_PROTOCOL
})

const ecr = new AWS.ECR({
  region: AWS_ECR_REGION,
  accessKeyId: AWS_ECR_ACCESS_KEY_ID,
  secretAccessKey: AWS_ECR_SECRET_ACCESS_KEY
})

const getTag = (slug, userId) => `${slug}.${userId}`
const getRepo = registry => `${registry}/${AWS_ECR_REPO}`
const getImageName = (registry, tag) => `${getRepo(registry)}:${tag}`

const getCreds = async () => {
  const token = await new Promise((resolve, reject) =>
    ecr.getAuthorizationToken({}, (err, data) =>
      err ? reject(err) : resolve(data)
    )
  )
  const { proxyEndpoint, authorizationToken } = token.authorizationData[0]
  const [ username, password ] = Buffer.from(authorizationToken, 'base64').toString().split(':')
  const registry = proxyEndpoint.replace('https://', '')
  return { registry, authconfig: { username, password } }
}

const commit = async (container, registry, tag, pause = false) => {
  await container.commit({ repo: getRepo(registry), tag, pause })
  return docker.getImage(getImageName(registry, tag))
}

const push = async (registry, image, authconfig) => {
  await image.tag({ repo: registry })
  const stream = await image.push({ registry, authconfig })
  await _waitForStream(stream)
}

const pull = async (registry, tag, authconfig) => {
  const imageName  = getImageName(registry, tag)
  const stream = await docker.pull(imageName, { authconfig })
  await _waitForStream(stream)
  return restoreId
}

const _waitForStream = async stream => {
  return new Promise((resolve, reject) =>
    docker.modem.followProgress(stream, err => err ? reject(err) : resolve())
  )
}

(async () => {
    const container = docker.getContainer('container-id')
    const { registry, authconfig } = await getCreds()
    const image = await commit(container, registry, tag)
    // this is where it fails to find an image
    await push(registry, image, authconfig)
})()
```

**Comment by thenengah** [comment]
I solved this by connecting directly to the worker node using `dockerode`.

**Comment by lehno** [comment]
Hey, what was your fix for this?
