### ISSUE TITLE
docker service update api throwing `mismatched Runtime and *Spec fields`

### ISSUE THREAD

**Issue by rightisleft** [apocas/dockerode#525]
Hello, I'm currently attempting to run an update action on an existing service. Before modifying anything i'm trying to get a 200 response from the update api. On all of my calls i get the following response from docker 

```
mismatched Runtime and *Spec fields
```

I've included the docker version on the object per other threads. Here is my code 

```
            // https://forums.docker.com/t/solved-force-update-a-service-with-the-rest-api-does-not-work-as-expected/62779/2

            let serviceManager: Dockerode.Service = await this.swarm.docker.getService(serviceName)
            const inspected: ServiceInfoListItem = await serviceManager.inspect();
            console.log('inspected: ', inspected.Version);
            console.log('inspected: ', inspected.CreatedAt);
            console.log('inspected: ', inspected.Spec.Networks);

            // inspected.Spec.Networks = [{Target: this.template.Name}];
            inspected.Spec.TaskTemplate.ForceUpdate = 1
            inspected.version = inspected.Version.Index;

            let response: { Warnings?: string; } = await serviceManager.update(inspected);
```
I get the following output:

```
inspected:  { Index: 262 }
inspected:  2019-06-21T14:51:34.011603399Z
inspected:  undefined
{ Error: (HTTP code 400) unexpected - mismatched Runtime and *Spec fields
     at /app/node_modules/docker-modem/lib/modem.js:257:17
     at getCause (/app/node_modules/docker-modem/lib/modem.js:287:7)
     at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:256:5)
     at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:232:14)
     at IncomingMessage.emit (events.js:187:15)
     at IncomingMessage.EventEmitter.emit (domain.js:441:20)
     at endReadableNT (_stream_readable.js:1094:12)
     at process._tickCallback (internal/process/next_tick.js:63:19)
   reason: undefined,
   statusCode: 400,
   json: { message: 'mismatched Runtime and *Spec fields' } } Promise {
   <rejected> { Error: (HTTP code 400) unexpected - mismatched Runtime and *Spec fields
       at /app/node_modules/docker-modem/lib/modem.js:257:17
       at getCause (/app/node_modules/docker-modem/lib/modem.js:287:7)
       at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:256:5)
       at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:232:14)
       at IncomingMessage.emit (events.js:187:15)
       at IncomingMessage.EventEmitter.emit (domain.js:441:20)
       at endReadableNT (_stream_readable.js:1094:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     reason: undefined,
     statusCode: 400,
     json: { message: 'mismatched Runtime and *Spec fields' } } }
```

**Comment by rightisleft** [comment]
This was caused by passing inspect instead of inspect.Spec
```
            let response: { Warnings?: string; } = await serviceManager.update(inspected.Spec);
```
