### ISSUE TITLE
Callback is not a function [Question]

### ISSUE THREAD

**Issue by Xx-Parks-xX** [apocas/dockerode#528]
I was trying simple 'Hello world' using example on README:

```
var Docker = require('dockerode');
var docker = new Docker({socketPath: '/var/run/docker.sock'});

//callback
docker.run('hello-world', process.stdout, function (err, data, container) {
	console.log(data.StatusCode);
});
```

But this returns:
```
/src/app/node_modules/dockerode/lib/docker.js:1411
    if (err) return callback(err, null, container);
                    ^

TypeError: callback is not a function
    at handler (/src/app/node_modules/dockerode/lib/docker.js:1411:21)
    at /src/app/node_modules/dockerode/lib/docker.js:73:23
    at /src/app/node_modules/docker-modem/lib/modem.js:265:7
    at getCause (/src/app/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/src/app/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/src/app/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I need to define all params ?
`Docker.prototype.run = function(image, cmd, streamo, createOptions, startOptions, callback)`

**Comment by Xx-Parks-xX** [comment]
My bad, I don't see that cmd is required, empty array fix it !
