### ISSUE TITLE
Running the example createContainer function

### ISSUE THREAD

**Issue by dannysmc95** [apocas/dockerode#543]
Hi,

I am using your API with Node.JS and I tried following the createContainer example:
```
// Trialling both dockerode-promise-wrapper and dockerode
const DockerCallback = require('dockerode');
const dockerOrigin = new DockerCallback();
dockerOrigin.createContainer({Image: 'ubuntu', Cmd: ['/bin/bash'], name: 'ubuntu-test'}, function (err, container) {
	console.error(err);
	console.log(container);
});
```

But I get the following error:
```
Error: (HTTP code 404) no such container - No such image: ubuntu:latest 
    at <project_dir>/node_modules/docker-modem/lib/modem.js:296:17
    at getCause (<project_dir>/node_modules/docker-modem/lib/modem.js:326:7)
    at Modem.buildPayload (<project_dir>/node_modules/docker-modem/lib/modem.js:295:5)
    at IncomingMessage.<anonymous> (<project_dir>/node_modules/docker-modem/lib/modem.js:270:14)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  reason: 'no such container',
  statusCode: 404,
  json: { message: 'No such image: ubuntu:latest' }
}
```

Docker Version:
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Node Version: v12.8.0
NPM Version: 6.13.0

And then I am using macOS Mojave, Version 10.14.5

Thanks,
Danny

**Comment by apocas** [comment]
Do you have the ubuntu image?

Pull the image before running that code:
docker pull ubuntu

**Comment by dannysmc95** [comment]
Oh I see, sorry I thought it would automatically pull it 🤦‍♂ - thank you.

**Comment by ChristopherHButler** [comment]
@dannysmc95 Do you have a code snippet of how you resolved this? I was trying to follow [this tutorial ](https://medium.com/@johnnyeric/how-to-reproduce-command-docker-run-via-docker-remote-api-with-node-js-5918d7b221ea) on medium but i am getting the same error it seems for 'alpine:latest'. Strange that the official docs do not show a complete example.
