### ISSUE TITLE
image api: invalid image name throws asynchronously

### ISSUE THREAD

**Issue by gramakri** [apocas/dockerode#548]
If the image name is of invalid format, dockerode throws asynchronously. There is no way to catch this error using try/throw or callback.

```
let Docker = require('dockerode');
  
const gConnection = new Docker({ socketPath: '/var/run/docker.sock' });

gConnection.getImage('https://foo').remove({}, function (error) {
    console.log(error);
});
```
The output of above is:
```
_http_client.js:70
      throw new ERR_INVALID_DOMAIN_NAME();
      ^

TypeError [ERR_INVALID_DOMAIN_NAME]: Unable to determine the domain name
    at new ClientRequest (_http_client.js:70:13)
    at Object.request (http.js:42:10)
    at h.request (/home/girish/tmp/node_modules/docker-modem/lib/http.js:51:52)
    at h.get (/home/girish/tmp/node_modules/docker-modem/lib/http.js:80:19)
    at ClientRequest.<anonymous> (/home/girish/tmp/node_modules/docker-modem/lib/http.js:69:40)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
```

**Comment by gramakri** [comment]
From what I can make out, the underlying issue is that docker-modem makes a call to http(s).get asynchronously. Unfortunately, that function throws an exception if the url is invalid - https://stackoverflow.com/questions/34933229/why-is-this-basic-node-js-error-handling-not-working . The exception throw happens in node code here - https://github.com/nodejs/node/blob/master/lib/https.js#L285

**Comment by gramakri** [comment]
image.get() also has the same issue. i changed the title of this report accordingly.

**Comment by josser** [comment]
You shouldn't include http:// in image name. If it stored in some private registry just specify host w/o http/https

**Comment by gramakri** [comment]
@josser The point is that it throws an un-catchable error. I am OK if it throws an exception but can be caught somehow.

**Comment by gramakri** [comment]
This issue still persists
