### ISSUE TITLE
Weird behavor on Windows (pull not awaited)

### ISSUE THREAD

**Issue by xobotyi** [apocas/dockerode#595]
Strange behavior on windows while attempting to create container:
Assuming that i dont have yet `alpine` image on the machine, performing 
``` javascript
import * as Dockerode from 'dockerode';

(async () => {
  const Docker = new Dockerode();

  const image = 'alpine';

  const container = await Docker.createContainer({
    Image: image,
    Tty: true,
    AttachStdout: true,
    AttachStderr: true,
  });

  await container.start();

  await container.stop();
  await container.remove();

  return true;
})();
```
Will end with following error no matter how many times i will run the code:
```
$ node_modules\.bin\ts-node .\src\test.ts
(node:33936) UnhandledPromiseRejectionWarning: Error: (HTTP code 404) no such container - No such image: alpine:latest
    at node_modules\docker-modem\lib\modem.js:301:17
    at getCause (node_modules\docker-modem\lib\modem.js:331:7)
    at Modem.buildPayload (node_modules\docker-modem\lib\modem.js:300:5)
    at IncomingMessage.<anonymous> (node_modules\docker-modem\lib\modem.js:275:14)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.32s.
```

Then if i will try to pull an image manually:
``` javascript
import * as Dockerode from 'dockerode';

(async () => {
  const Docker = new Dockerode();

  const image = 'alpine';
  await Docker.pull(image, {});
  const container = await Docker.createContainer({
    Image: image,
    Tty: true,
    AttachStdout: true,
    AttachStderr: true,
  });

  await container.start();

  await container.stop();
  await container.remove();

  return true;
})();
```

First call will end up the same:
```
$ node_modules\.bin\ts-node .\src\test.ts
(node:39924) UnhandledPromiseRejectionWarning: Error: (HTTP code 404) no such container - No such image: alpine:latest
    at node_modules\docker-modem\lib\modem.js:301:17
    at getCause (node_modules\docker-modem\lib\modem.js:331:7)
    at Modem.buildPayload (node_modules\docker-modem\lib\modem.js:300:5)
    at IncomingMessage.<anonymous> (node_modules\docker-modem\lib\modem.js:275:14)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 4.66s.
```

But this time image was successfully pulled from hub and sequential script call performed with no errors.

I sippose that somewhy pull is not not waiting for the pull process end and fast-forwarding to container creation.

**Comment by xobotyi** [comment]
As it figures - `Docker.pull` returns a stream (even if awaited) so i have to wait till stream end (i'm doing it with `streamToPromise` lib) so it should look like:
``` javascript
const imageName = 'alpine';

await streamToPromise(await Docker.pull(imageName));
const image = await Docker.getImage(imageName);

const container = await Docker.createContainer({ Image: imageName, Tty: true });
