### ISSUE TITLE
Updating aliases fails on service update

### ISSUE THREAD

**Issue by rightisleft** [apocas/dockerode#604]
I'm trying to add a new network aliases to a service. When i issue the update command i get the following error:

```
Error: (HTTP code 500) server error - rpc error: code = Unknown desc = update out of sequence 
    at /app/node_modules/docker-modem/lib/modem.js:301:17
    at getCause (/app/node_modules/docker-modem/lib/modem.js:331:7)
    at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:300:5)
    at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:275:14)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

The code:

```
    async updateAliasesForNetworkedService(serviceName: string, aliases: string[]): Promise<Service> {
        let service: Dockerode.Service = await this.swarm.docker.getService(serviceName);        
        let inspected: Service = await service.inspect();
        console.log('Inspected TaskTemplate:  ', inspected.Spec.TaskTemplate.Networks);

        const activeNetwork: NetworkAttachmentConfig = inspected.Spec.Networks.find(na => na.Target === this.network.id);
        activeNetwork.Aliases = aliases;
        const networks = inspected.Spec.TaskTemplate.Networks ? inspected.Spec.TaskTemplate.Networks : [];
        networks.push(activeNetwork);

        inspected.Spec.TaskTemplate.Networks = networks;
        inspected.Spec.TaskTemplate.ForceUpdate = inspected.Spec.TaskTemplate.ForceUpdate + 1;
        inspected.Spec.Mode.Replicated.Replicas = inspected.Spec.Mode.Replicated.Replicas;

        let response: any = await service.update({...inspected.Spec, version: inspected.Version.Index});
        console.log(`response from updateAliasesForNetworkedService ${serviceName}:`, response);

        inspected = await service.inspect();
        return inspected;
    }
```

The Opts Values:

```
{
  "Name": "generic_100",
  "Labels": {
    "com.scuba.config": "{\"index\":2,\"contentUrl\":\"https://jsonplaceholder.typicode.com/posts/2\",\"imageUrl\":\"https://picsum.photos/id/2/200/300\"}",
    "com.scuba.name": "generic_100",
    "com.scuba.namespace": "local_ship",
    "com.scuba.tag": "custom-tag",
    "com.scuba.type": "generic",
    "com.scuba.typeId": "100",
    "com.scuba.uuid": "c0025b85-9d10-4d8d-aca1-f844f2c947a3"
  },
  "TaskTemplate": {
    "ContainerSpec": {
      "Image": "scuba/shipgeneric:custom-tag",
      "Env": [
        "scuba_JOB_JSON_STRING={\"index\":2,\"contentUrl\":\"https://jsonplaceholder.typicode.com/posts/2\",\"imageUrl\":\"https://picsum.photos/id/2/200/300\"}"
      ],
      "Isolation": "default"
    },
    "ForceUpdate": 1,
    "Runtime": "container",
    "Networks": [
      {
        "Target": "idpcw6t0jfw7iwhhohrsc16nj",
        "Aliases": [
          "generic_100",
          "slot_2",
          "updated_to_alias_2"
        ]
      }
    ]
  },
  "Mode": {
    "Replicated": {
      "Replicas": 1
    }
  },
  "Networks": [
    {
      "Target": "idpcw6t0jfw7iwhhohrsc16nj",
      "Aliases": [
        "generic_100",
        "slot_2"
      ]
    }
  ],
  "EndpointSpec": {
    "Mode": "vip",
    "Ports": [
      {
        "Protocol": "tcp",
        "TargetPort": 80,
        "PublishMode": "ingress"
      }
    ]
  },
  "version": 803514
}
```

**Comment by xxAROX** [comment]
bruh
