### ISSUE TITLE
data.on is not a function

### ISSUE THREAD

**Issue by Tatuck** [apocas/dockerode#640]
Hello. I am trying to build a Dockerfile with this code:
```js
docker.buildImage({
    src:["/<full-path>/images/Test2/Dockerfile"]
}, {
    t:imageTag
}, function(err, stream){
    if(err){
        console.log(err);
    }
});
```
But I am getting this error:
```
TypeError: data.on is not a function
    at Modem.buildRequest (<full-path>/node_modules/docker-modem/lib/modem.js:299:10)
    at Modem.dial (<full-path>/node_modules/docker-modem/lib/modem.js:213:8)
    at build (<full-path>/node_modules/dockerode/lib/docker.js:293:18)
    at Docker.buildImage (<full-path>/node_modules/dockerode/lib/docker.js:305:12)
    at <full-path>/routes/createimage.js:66:20
    at Layer.handle [as handle_request] (<full-path>/node_modules/express/lib/router/layer.js:95:5)
    at next (<full-path>r/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (<full-path>/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (<full-path>/node_modules/express/lib/router/layer.js:95:5)
    at <full-path>/node_modules/express/lib/router/index.js:281:22
```

I also tried using: 
```js
docker.buildImage(
    "<full-path>/images/Test2/Dockerfile",
    {
        t:imageTag
    }, function(err, stream){
    if(err){
        console.log(err)
        return res.status(500).send(err.message);
    }
    stream.pipe(process.stdout);
});
```
But I am getting this other error:
```
Error: (HTTP code 500) server error - unexpected EOF 
    at <full-path>/node_modules/docker-modem/lib/modem.js:315:17
    at IncomingMessage.<anonymous> (<full-path>/node_modules/docker-modem/lib/modem.js:342:9)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  reason: 'server error',
  statusCode: 500,
  json: null
}
```

The Dockerfile is:
```
FROM python
COPY . /app
CMD python /app/app.py
```
And `/app/app.py` is a script which writes `Hello World!` to the console.

What am I doing wrong? 
Thanks

**Comment by Tatuck** [comment]
Solved using [tar-fs](https://www.npmjs.com/package/tar-fs) like this:
```js
const tar = require("tar-fs");
docker.buildImage(
    tar.pack("<path>/images/Test2/"),
    {
        t:imageTag
    }, function(err, stream){
    if(err){
        console.log(err)
        return res.status(500).send(err.message);
    }
    stream.pipe(process.stdout);
});
```
`/images/Test2/` contains the `Dockerfile` and the python script. You have to use the path to the containing folder, not to the `Dockerfile`.
