### ISSUE TITLE
Error: (HTTP code 400) unexpected - failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "ls": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by thallosaurus** [apocas/dockerode#654]
I'm trying to create the following container and I get the mentionend Errorcode everytime I try to start the container. It gets created but fails to start each time

Container-Config:
```
return dockerClient.createContainer({
  Image: 'alpine',
  AttachStdin: false,
  AttachStdout: false,
  AttachStderr: false,
  Tty: false,
  Cmd: ['ls', '-la'],
  OpenStdin: false,
  StdinOnce: false
});
```

Here's the raw errorobject:
```
Error: (HTTP code 400) unexpected - failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "ls": executable file not found in $PATH: unknown
    at /home/thallosaurus/code/DockerVM/node_modules/docker-modem/lib/modem.js:324:17
    at getCause (/home/thallosaurus/code/DockerVM/node_modules/docker-modem/lib/modem.js:354:7)
    at Modem.buildPayload (/home/thallosaurus/code/DockerVM/node_modules/docker-modem/lib/modem.js:323:5)
    at IncomingMessage.<anonymous> (/home/thallosaurus/code/DockerVM/node_modules/docker-modem/lib/modem.js:295:14)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1342:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  reason: undefined,
  statusCode: 400,
  json: {
    message: 'failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "ls": executable file not found in $PATH: unknown'
  }
```

what could it be? how can I fix this?

**Comment by thallosaurus** [comment]
I found the error!
It happens only when you set Image to null or undefined when creating a container
