### ISSUE TITLE
Specifying socketPath but Dockerode is using HTTP.

### ISSUE THREAD

**Issue by Fumaz** [apocas/dockerode#747]
Hi, I'm initializing dockerode like this:

```ts
const docker = new Docker({socketPath: '/var/run/docker.sock'});
```

but when I use it, it gives the following error:

```
Could not get container information. ConnectionRefused: Unable to connect. Is the computer able to access the url?
path: "http://localhost/containers/b81d1747b4d9/json"
```

I am using Bun.

**Comment by ptrxyz** [comment]
An into the same problem ... not sure how that would happen. Maybe a permission thing?

**Comment by ptrxyz** [comment]
Maybe it matters: my Docker daemon version is 1.24, this is my test code:

```ts        
import Docker from 'dockerode';
const docker = new Docker({ socketPath: '/var/run/docker.sock' });
```

The error:

```
/tmp/dockerode · sudo bun run index.ts
Error: ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost/containers/json?all=true"
```

Debug info:
```
/tmp/dockerode · ls -la /var/run/docker.sock
srw-rw---- 1 root docker 0 Oct 18 16:16 /var/run/docker.sock

/tmp/dockerode · docker info
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc sysbox-runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8c087663b0233f6e6e2f4515cee61d49f14746a8.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.7-zen2-1-zen
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.26GiB
 Name: nine
 ID: 29c770ff-e2ff-4c97-84e9-1e3da89486ae
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by apocas** [comment]
Investigating

**Comment by apocas** [comment]
I can't reproduce that :(
Tried exactly the same scenario bun and nodejs.

**Comment by hazelnutcloud** [comment]
running into same problem

**Comment by hazelnutcloud** [comment]
This seems to be a problem with bun. See https://github.com/oven-sh/bun/issues/6055

**Comment by apocas** [comment]
Now I can reproduce it :) 
Indeed is seems something related with bun, not much we can do right now.

**Comment by recanman** [comment]
Temporary solution I'm using:

```bash
socat TCP-LISTEN:3000,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock
```

Use it like this:
```ts
new Dockerode({protocol: 'http', host: 'localhost', port: 3000})
```

**Comment by recanman** [comment]
There is [a pull request](https://github.com/oven-sh/bun/pull/2777), but no response yet.

**Comment by Anprotaku** [comment]
@recanman it looks like they merged another pull request that should fix it
https://github.com/oven-sh/bun/pull/9284

**Comment by recanman** [comment]
Great, thank you!
Mentioning author: @Fumaz

**Comment by dionjwa** [comment]
I am using `dockerode@4.0.2` via deno, and I am still getting this issue.

**Comment by devingfx** [comment]
Same issue with Deno 1.43.6, dockerode 4.0.2, with:
```js
import Docker from 'npm:dockerode'
const docker = new Docker({socketPath: '/var/run/docker.sock'})
const images = await docker.listImages()
console.log( images )
```

Got: 
```bash
error: Uncaught (in promise) TypeError: error sending request for url (http://localhost/images/json): error trying to connect: tcp connect error: Connection refused (os error 111)
    at async node:http:397:21
```

**Comment by recanman** [comment]
That is unrelated to this issue. Open a new issue.

**Comment by Karrq** [comment]
I'm also getting the same issue with Deno 2. 

I think it's related due to the fact that it's the same issue as what bun had, and other deno users will be able to find this and not waste time debugging why it's happening

**Comment by LazerJesus** [comment]
same issue with deno 2.  is there an issue yet? couldnt find it if there is

**Comment by DanielSharkov** [comment]
> Same issue with Deno 1.43.6, dockerode 4.0.2, with:
> 
> import Docker from 'npm:dockerode'
> const docker = new Docker({socketPath: '/var/run/docker.sock'})
> const images = await docker.listImages()
> console.log( images )
> Got:
> 
> error: Uncaught (in promise) TypeError: error sending request for url (http://localhost/images/json): error trying to connect: tcp connect error: Connection refused (os error 111)
>     at async node:http:397:21

Running this code on Deno 2.2.1 and dockerode 4.0.4 results for me in:
```
error: Uncaught (in promise) BadResource: Bad resource ID
    at node:http:327:27
    at ClientRequest._writeHeader (node:http:440:7)
    at ClientRequest._flushHeaders (node:_http_outgoing:382:12)
    at Socket.onConnect (node:http:486:16)
    at Socket.emit (ext:deno_node/_events.mjs:405:35)
    at PipeConnectWrap._afterConnect [as oncomplete] (node:net:159:12)
    at Pipe.afterConnect (ext:deno_node/internal_binding/connection_wrap.ts:43:11)
    at ext:deno_node/internal_binding/pipe_wrap.ts:123:14
    at eventLoopTick (ext:core/01_core.js:177:7)
```

But fortunately, I found a great workaround **for Deno** here: https://github.com/denoland/deno/issues/20255#issuecomment-2623293943

Still, I had to tweak it slightly. The original `Promise.all` implementation didn't make sense and didn't work for me. Here's my improved version:
```javascript
import { copy } from 'jsr:@std/io';
import { ClientRequest } from 'node:http';

function startDockerProxy(proxyPort = 2375): () => Promise<void> {
	const originalSocketHandler = ClientRequest.prototype.onSocket;
	ClientRequest.prototype.onSocket = function (socket) {
		socket.unref = function () {
			return this;
		};
		return originalSocketHandler.call(this, socket);
	};

	Deno.env.set('DOCKER_HOST', `tcp://localhost:${proxyPort}`);
	const tcpListener = Deno.listen({ port: proxyPort });
	const handleConnections = async () => {
		for await (const tcpConn of tcpListener) {
			dockerProxyHandleConnection(tcpConn);
		}
	};

	const connectionsHandler = handleConnections();
	return async () => {
		tcpListener.close();
		ClientRequest.prototype.onSocket = originalSocketHandler;
		await connectionsHandler;
	};
}

async function dockerProxyHandleConnection(tcpConn: Deno.Conn) {
	let unixConn: Deno.Conn | undefined;
	try {
		unixConn = await Deno.connect({ transport: 'unix', path: '/var/run/docker.sock' });

		const tcpToUnixPromise = copy(tcpConn, unixConn).catch((err) => {
			if (err.code !== 'EPIPE' && err.code !== 'EINTR') {
				console.error('[TCP -> Unix] error:', err);
			}
		});
		const unixToTcpPromise = copy(unixConn, tcpConn).catch((err) => {
			if (err.code !== 'EPIPE' && err.code !== 'EINTR') {
				console.error('[Unix -> TCP] error:', err);
			}
		});
		await Promise.race([tcpToUnixPromise, unixToTcpPromise]);
	} catch (error) {
		console.error('Docker proxy connection error:', error);
	} finally {
		// Extra safety: ensure connections are closed even if something goes wrong above
		try {
			unixConn?.close();
			tcpConn.close();
		} catch (err) {
			console.log('FATAL: closing connections failed: ', err);
		}
	}
}
```

Then I'm just using it like:
```javascript
import { ArangoDBContainer } from '@testcontainers/arangodb';
import { Database } from 'arangojs';

export async function connectArangoDbContainer(dbName: string) {
	const stopDockerProxy = startDockerProxy();
	const arangoDbContainer = await new ArangoDBContainer('arangodb:3.11', '').start();

	const arangoDb = new Database();
	// ...

	const stopContainer = async () => {
		await arangoDbContainer.stop();
		await stopDockerProxy();
	};
	return { arangoDbContainer, arangoDb, stopContainer };
}

const { arangoDb, stopContainer } = connectArangoDbContainer('test');
// ... do smth
await stopContainer();
```

Make sure to stop both the container and the proxy properly. Don’t just call `arangoDbContainer.stop()` — use the stop handler to first stop the container and then the proxy, ensuring all listeners are closed.

I'm on macOS. I don't know if this will work on windows systems.

**Comment by marcus-sa** [comment]
I don't have any issues with Bun.

**Comment by recanman** [comment]
@marcus-sa 
[I suggest you read the thread before responding](https://github.com/apocas/dockerode/issues/747#issuecomment-1982865916).

**Comment by kravetsone** [comment]
> [@marcus-sa](https://github.com/marcus-sa) [I suggest you read the thread before responding](https://github.com/apocas/dockerode/issues/747#issuecomment-1982865916).

it is broken for me 1.2.13
